#+HUGO_BASE_DIR: ~/projects/exaclior.github.io/
#+HUGO_SECTION: posts
#+TITLE: Thinking Functionally with Haskell
#+SUBTITLE: What is functional programming?
#+AUTHOR: Yusheng Zhao
#+DATE: <2024-06-27 Thu>
#+EXPORT_HUGO_TAGS: t
#+filetags: Haskell FunctionalProgramming

* Introduction
This is the first of a series of blog posts that cover each chapter of the book
"Thinking Functionally with Haskell" by Richard Bird [[cite:&bird2015thinking]]. The
goal of this book, and incidentally these posts, will not be to teach you
Haskell but to teach you ways of thinking in functional programming. I will
assume that you have basic knowledge in at least one statically typed language
like ~C~. I hope we will both become a better programmer at the end of this
journey.

* What is functional programming?
So you may ask, what is functional programming? Let us answer this question
through an example. Consider the problem of counting the most common $n$ words
in some text.

** Formulating Problem in Simple Mathematical Notation
The first step in solving the problem is to formulate it clearly. The input is
some text plus an integer $n$. For example, it could be an excerpt from /War and
Peace/. The output is a list of words each followed by the number of times they
appeared in the text. For simplicity, we could combine them into another text.
In the format of each word followed by the number they appeared on each line.
For example, ~(Foo,3) (Bar,2) (Hey 1)~ will be outputed as ~"Foo: 3 \n Bar 2 \n
Hey 1 \n"~.

An object that takes a string of input and outputs another string can be thought
of as a map. In Haskell, you may express such map as

#+begin_src haskell
commonWords :: Int -> [Char] -> [Char]
#+end_src

The above is the way you denote the kind of map a function represents in
Haskell. We know this is a function that takes in


If you don't like using ~[Char]~ you could define *synonyms* for types.

#+begin_src haskell
type Text = [Char]
type Word = [Char]
#+end_src

Details on type system aside, we see that Haskell is able to state the problem
in an elegant and abstract way.

** Implementation one function at a time

Now it's time to think about how to


1. "Functional programming is a method of program construction that emphasises
   functions and their application rather than commands and their execution"

   You break down a problem into smaller problems and solve them separately.
   Chaining them together to solve the original problem.

   For example,

   #+begin_src haskell
foo1 :: a -> b
foo2 :: b -> c
foo3 :: c -> d

solver x  = (foo3 . foo2 . foo1)  a
-- the same as
solver x =  foo3 (foo2 (foo1 a))
   #+end_src



* Exercises Answers Typed


* Outro
I hope you enjoyed this post. The accompaning code is in this [[https://github.com/exAClior/common-words][repo]].


* Left-overs
Here are a list of concepts mentioned in this chapter but I do not understand
yet.

1. "Functional programming has a simple mathematical basis that supports
   equational reasoning about the properties of programs"

* Reference
** References
   bibliographystyle:apalike
   [[bibliography:./references/bird.bib][bibliography:./references/bird.bib]]
